version: "3.2"
volumes:
  wgt_data:
services:
  test_data_manager:
    build:
      context: ../
      dockerfile: Dockerfile.test-data-manager
      args:
        GO_BUILD_TAGS: "dev"
    logging:
      # test_data_manager's logs are too noisy
      driver: none
    environment:
      - PORT=5200
    volumes:
      - wgt_data:/app/test-data-manager/data
    command:
      ["-source", "/app/test-data-manager/integration-data.yaml", "-keepAlive"]
  whatgotdone_backend:
    build:
      context: ../
      args:
        NPM_BUILD_MODE: staging
        GO_BUILD_TAGS: staging
    environment:
      - PORT=3123
      - CSRF_SECRET_SEED=dummy-staging-seed
      - USERKIT_SECRET=dummy.dummy
      - PUBLIC_GCS_BUCKET=whatgotdone-public-staging
    volumes:
      - ../gcp-service-account-staging.json:/app/gcp-service-account-staging.json
      - ./:/app/integration
      - wgt_data:/app/data
  # Run What Got Done behind an nginx proxy to better simulate how it will run
  # in production.
  whatgotdone:
    image: "nginx:latest"
    ports:
      - 80:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    logging:
      # nginx's logs are duplicates of whatgotdone_backend
      driver: none
    depends_on:
      - whatgotdone_backend
  cypress:
    image: "mtlynch/cypress:8.1.0-chrome91-2"
    command: ["--browser", "chrome"]
    depends_on:
      - whatgotdone
      - test_data_manager
    environment:
      - CYPRESS_baseUrl=http://whatgotdone
      - CYPRESS_testDataManagerUrl=http://test_data_manager:5200
      # Uncomment the following line for verbose Cypress debugging output.
      #- DEBUG=cypress:server:request,cypress:server:server,cypress:server:proxy,cypress:network:agent,cypress:server:browsers

      # Set test timezone to Los Angeles so that we're more likely to catch
      # incorrect UTC vs. local date translations.
      - TZ=America/Los_Angeles
    working_dir: /integration
    volumes:
      - ./:/integration
