version: "3.2"
services:
  firestore_emulator:
    image: mtlynch/firestore-emulator:20191115T1224
    environment:
      - FIRESTORE_PROJECT_ID=dummy-local-gcp-project
      - PORT=8080
  test_data_manager:
    build:
      context: ../
      dockerfile: Dockerfile.test-data-manager
      args:
        GO_BUILD_TAGS: "dev"
    environment:
      - GOOGLE_CLOUD_PROJECT=dummy-local-gcp-project
      - FIRESTORE_EMULATOR_HOST=firestore_emulator:8080
      - PORT=5200
    command:
      ["-source", "/app/test-data-manager/integration-data.yaml", "-keepAlive"]
    depends_on:
      - firestore_emulator
  whatgotdone:
    build:
      context: ../
      args:
        NPM_BUILD_MODE: staging
        GO_BUILD_TAGS: "staging"
    depends_on:
      - firestore_emulator
    environment:
      - PORT=3123
      - CSRF_SECRET_SEED=dummy-staging-seed
      - USERKIT_SECRET=dummy.dummy
      - GOOGLE_CLOUD_PROJECT=dummy-local-gcp-project
      - FIRESTORE_EMULATOR_HOST=firestore_emulator:8080
    volumes:
      - ../service-account-creds-staging.json:/app/service-account-creds-staging.json
      - ./:/app/integration
  cypress:
    image: "cypress/included:4.2.0"
    command: ["--browser", "chrome"]
    depends_on:
      - whatgotdone
    environment:
      - CYPRESS_baseUrl=http://whatgotdone:3123
      - CYPRESS_testDataManagerUrl=http://test_data_manager:5200
      # Uncomment the following line for verbose Cypress debugging output.
      #- DEBUG=cypress:server:request,cypress:server:server,cypress:server:proxy,cypress:network:agent,cypress:server:browsers

      # Set test timezone to Los Angeles so that we're more likely to catch
      # incorrect UTC vs. local date translations.
      - TZ=America/Los_Angeles
    working_dir: /integration
    volumes:
      - ./:/integration
